### ISSUE TITLE
The display name is listing a 'n'

### ISSUE THREAD

**Issue by binarygary** [aliviarcarruth/slackbot#1]
https://github.com/aliviarcarruth/slackbot/blob/d7eba7e19a7e1b36705a557a85157a151b4042bd/index.js#L10

**Comment by aliviarcarruth** [comment]
@binarygary amazing, thanks for spotting that! 
![image](https://user-images.githubusercontent.com/30294849/121422593-633c0d00-c93d-11eb-85e8-61e686012387.png)

**Comment by aliviarcarruth** [comment]
Fixed with commit [a3d9728](https://github.com/aliviarcarruth/slackbot/commit/a3d9728a1beb76ef7d7605bafbfb57d0c4de283a)
